CREATE TABLE IF NOT EXISTS stat
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(100) NOT NULL,
    uri       varchar(100) NOT NULL,
    ip        varchar(100) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE
);